# Introduction to NumPy

No matter what field of Data Science you for into, NumPy is useful.  Let's start by imporing NumPy.  When we import NumPy, we generally import it as np.  This is the convention most people use,

In [2]:
import numpy as np

np.[TAB] will bring up all of the built-in functions that are inhetent to NumPy.

In [3]:
np?

Go to http://www.numpy.org for more detailed information

In [4]:
L = list(range(10))

In [6]:
type(L[0])

int

In [7]:
L2 = [str(c) for c in L]

In [8]:
print(L2)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [9]:
type(L2[0])

str

In [11]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [12]:
import array
L = list(range(10))
A = array.array('i',L)

In [13]:
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#integer array
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [17]:
np.array([3.14, 4, 2, 3])

array([ 3.14,  4.  ,  2.  ,  3.  ])

In [18]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [20]:
#Create a length 10 integer array filled with zeros
np.zeros(19, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])